# automatically generated by g-sorcery
# please do not edit this file

EAPI=7
PYTHON_COMPAT=( python{3_6,3_7} )

inherit distutils-r1

DESCRIPTION="DeepSpeech is an open source Speech-To-Text engine"
SRC_URI="https://github.com/mozilla/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz"

HOMEPAGE="https://github.com/mozilla/DeepSpeech"
LICENSE="MPL-2.0"

SLOT="0"
KEYWORDS="~amd64 ~x86"
