#!/bin/sh

URL=https://bugs.gentoo.org
PROFILEDIR=`echo ~/.local/share/epiphany-w3a-gentoo-bugs`

mkdir -p $PROFILEDIR
ln -sf /usr/share/applications/w3a-gentoo-bugs.desktop $PROFILEDIR/epiphany-w3a-gentoo-bugs.desktop
ln -sf /usr/share/pixmaps/w3a-gentoo-bugs.png $PROFILEDIR/app-icon.png
epiphany --application-mode --profile=$PROFILEDIR $URL
