# automatically generated by g-sorcery
# please do not edit this file

EAPI=7
PYTHON_COMPAT=( python{3_6,3_7,3_8,3_9} )

inherit distutils-r1

DESCRIPTION="An open source Shogi Game"
SRC_URI="https://github.com/johncheetham/gshogi/archive/v${PV}.tar.gz -> ${P}.tar.gz"

HOMEPAGE="http://johncheetham.com/projects/gshogi"
LICENSE="GPL-3"

SLOT="0"
KEYWORDS="~amd64 ~x86"

RDEPEND=""

