#!/bin/sh
#
# This script is enlightened by: http://wiki.gentoo.org/wiki/Distcc/Cross-Compiling
# fixme:
# 1. why "-g${0:$[-2]}", I think it should be "$(basename \"${0}\")"
# 2. how to adapt /usr/lib and /usr/lib64
#

hook_post_src_install() {
	if [ "${CATEGORY}/${PN}" == "sys-devel/distcc" ] ; then
		echo "exec /usr/lib64/distcc/bin/${CHOST}-g\${0:\$[-2]} \"\$@\"" > ${D}/usr/lib64/distcc/bin/${CHOST}-wrapper
		chmod 755 ${D}/usr/lib64/distcc/bin/${CHOST}-wrapper

		ln -sf ${CHOST}-wrapper ${D}/usr/lib64/distcc/bin/cc
		ln -sf ${CHOST}-wrapper ${D}/usr/lib64/distcc/bin/c++
		ln -sf ${CHOST}-wrapper ${D}/usr/lib64/distcc/bin/gcc
		ln -sf ${CHOST}-wrapper ${D}/usr/lib64/distcc/bin/g++
	fi
}
