#!/bin/sh

URL=http://bing.com
PROFILEDIR=`echo ~/.local/share/epiphany-w3a-bing`

mkdir -p $PROFILEDIR
ln -sf /usr/share/applications/w3a-bing.desktop $PROFILEDIR/epiphany-w3a-bing.desktop
epiphany --application-mode --profile=$PROFILEDIR $URL
