# automatically generated by g-sorcery
# please do not edit this file

EAPI=5
PYTHON_COMPAT=( python{2_7,3_6,3_7} )

inherit distutils-r1

DESCRIPTION="Implements a topological sort algorithm."
SRC_URI="https://pypi.python.org/packages/e5/d8/9bc1598ddf74410beba243ffeaee8d0b3ca7e9ac5cefe77367da497433e1/toposort-1.5.tar.gz"

HOMEPAGE="https://bitbucket.org/ericvsmith/toposort"
LICENSE="Apache-2.0"

SLOT="0"
KEYWORDS="~amd64 ~x86"

