# automatically generated by g-sorcery
# please do not edit this file

EAPI=6
PYTHON_COMPAT=( python{3_6,3_7,3_8} )

inherit distutils-r1

DESCRIPTION="The core module of Aliyun Python SDK."
SRC_URI="https://files.pythonhosted.org/packages/81/da/d8134e0637dfe7686651e2385e82baf3699aa20e5d2d9dee8743f8099c04/aliyun-python-sdk-core-2.13.14.tar.gz"
HOMEPAGE="http://develop.aliyun.com/sdk/python"
LICENSE="Apache-2.0"

SLOT="0"
KEYWORDS="~amd64 ~x86"
