# automatically generated by g-sorcery
# please do not edit this file

EAPI=5
PYTHON_COMPAT=( python{2_6,2_6,3_3,3_4,3_5} )

inherit distutils-r1

DESCRIPTION="The core module of Aliyun Python SDK."
SRC_URI="https://pypi.python.org/packages/ba/fe/a808aad2850e720651e29a00dce5a6727318c7a517d4a47429c176737b7c/aliyun-python-sdk-core-2.3.6.tar.gz"
HOMEPAGE="http://develop.aliyun.com/sdk/python"
LICENSE="Apache-2.0"

SLOT="0"
KEYWORDS="~amd64 ~x86"

