# automatically generated by g-sorcery
# please do not edit this file

EAPI=6
PYTHON_COMPAT=( python{3_6,3_7,3_8} )

inherit distutils-r1

DESCRIPTION="The ecs module of Aliyun Python sdk."
SRC_URI="https://files.pythonhosted.org/packages/02/d8/c30831b30f0097e8fbef74496fe9f3493bb172295be71acf8c2b7759bd34/aliyun-python-sdk-ecs-4.18.3.tar.gz"
HOMEPAGE="http://develop.aliyun.com/sdk/python"
LICENSE="Apache-2.0"

SLOT="0"
KEYWORDS="~amd64 ~x86"

RDEPEND="dev-python/aliyun-python-sdk-core"
