# automatically generated by g-sorcery
# please do not edit this file

EAPI=5
PYTHON_COMPAT=( python{2_6,2_7,3_3,3_4,3_5} )

inherit distutils-r1

DESCRIPTION="The ecs module of Aliyun Python sdk."
SRC_URI="https://pypi.python.org/packages/5c/ee/1aedf875514d178f0bf26835ed233eb0647846df3c941cc6478aa70fddf3/aliyun-python-sdk-ecs-4.0.0.tar.gz"
HOMEPAGE="http://develop.aliyun.com/sdk/python"
LICENSE="Apache-2.0"

SLOT="0"
KEYWORDS="~amd64 ~x86"

RDEPEND="dev-python/aliyun-python-sdk-core"
