# automatically generated by g-sorcery
# please do not edit this file

EAPI=6
PYTHON_COMPAT=( python{2_7,3_6,3_7} )

inherit distutils-r1

DESCRIPTION="Implements some tools for JSON"
SRC_URI="https://files.pythonhosted.org/packages/08/eb/3d294b939d5d314e4c9eba5ed958a2872c21f090ec9aa77aef9524308a71/json-spec-0.10.1.tar.gz"

HOMEPAGE="http://py.errorist.io/json-spec"
LICENSE="Apache-2.0"

SLOT="0"
KEYWORDS="~amd64 ~x86"

