#!/bin/sh

create_wine_dir ()
{
    # get params
    winedir=${1:?} ; shift			# only accept absolute path without trailing slash

    # exec wine command
    if [ ! -e "$winedir" ] ; then
        mkdir -p "$winedir"
    fi
    WINEPREFIX="$winedir" wineboot

    # change softlink to real directory in user directory
    userdir="$winedir/drive_c/users/$(id -un)"
    SAVEIFS=$IFS
    IFS=$'\n'
    for f in `find "$userdir" -print`
    do
        if [ ! -L "$f" ] ; then continue ; fi

        unlink $f
        mkdir $f
    done
}

create_link ()
{
    # get params
    srcdir=${1:?} ; shift			# only accept absolute path without trailing slash
    dstdir=${1:?} ; shift			# same as above
    dstdir_in="$dstdir/$(basename $srcdir)"

    # make dstdir in srcdir
    if [ ! -e "$dstdir_in" ] ; then
        mkdir -p "$dstdir_in"
    fi

    # do the job
    SAVEIFS=$IFS
    IFS=$'\n'
    for srcf in `find "$srcdir" -print`
    do
        # get inner filename
        f=${srcf:((${#srcdir}+1))}
        if [ "$f" == "" ] ; then continue ; fi

        # do the job
        if [[ -d "$srcf" && ! -L "$srcf" ]] ; then
            # create directory structure
            mkdir -p "$dstdir_in/$f"
        else
            # create softlink
            ln -s -f -t `dirname "$dstdir_in/$f"` $srcf
        fi
    done
    IFS=$SAVEIFS
}

get_cur_lang ()
{
    if [ ${LC_ALL:-x} != "x" ] ; then echo "$LC_ALL"
    elif [ ${LANG:-x} != "x" ] ; then echo "$LANG"
    elif [ ${LC_LANG:-x} != "x" ] ; then echo "$LC_LANG"
    else echo ""
    fi

    return 0
}

# Variables
GAMEDIR=		# fill by ebuild
DATADIR=		# fill by ebuild
CFGDIR=			# fill by ebuild

# Create wine directory
create_wine_dir "$DATADIR"
WINEPREFIX="$DATADIR" winetricks d3dx9

# Make links of "$GAMEDIR/*" to "$DATADIR"
if [ ! -e "$DATADIR/drive_c/Need for Speed(TM) Hot Pursuit" ] ; then
    create_link "$GAMEDIR/Need for Speed(TM) Hot Pursuit" "$DATADIR/drive_c"
fi

# Make configuration directory
mkdir -p "$CFGDIR"
rm -rf "$DATADIR/drive_c/users/$(id -un)/My Documents"
ln -sf "$CFGDIR" "$DATADIR/drive_c/users/$(id -un)/My Documents"

# Import the default registry file
WINEPREFIX="$DATADIR" regedit "$GAMEDIR/registry-patch/en.reg"

# Import the correct registry file
langu=$(get_cur_lang)
langu=${langu%%.*}
for f in `find "$GAMEDIR/registry-patch" -print`; do
    if [ "$langu" == "$(basename $f)" ] ; then
        WINEPREFIX="$DATADIR" regedit "$GAMEDIR/registry-patch/${langu}.reg"
done

# run the game
cd "$DATADIR/drive_c/Need for Speed(TM) Hot Pursuit"
WINEPREFIX="$DATADIR" wine Launcher.exe
xrandr -s 0
