# automatically generated by g-sorcery
# please do not edit this file

EAPI=7
PYTHON_COMPAT=( python{3_6,3_7} )

inherit distutils-r1

DESCRIPTION="KivyMD is a collection of Material Design compliant widgets for use with Kivy."
SRC_URI="https://github.com/kivymd/KivyMD/archive/${PV}.tar.gz -> ${P}.tar.gz"

HOMEPAGE="https://kivymd.readthedocs.io"
LICENSE="MIT"

SLOT="0"
KEYWORDS="~amd64 ~x86"

S="${WORKDIR}/KivyMD-${PV}"
