#!/bin/sh

URL=http://chiphell.com
PROFILEDIR=`echo ~/.local/share/epiphany-w3a-chiphell`

mkdir -p $PROFILEDIR
ln -sf /usr/share/applications/w3a-chiphell.desktop $PROFILEDIR/epiphany-w3a-chiphell.desktop
ln -sf /usr/share/pixmaps/w3a-chiphell.png $PROFILEDIR/app-icon.png
epiphany --application-mode --profile=$PROFILEDIR $URL
