#!/bin/sh

URL=https://gentoo.org
PROFILEDIR=`echo ~/.local/share/epiphany-w3a-gentoo`

mkdir -p $PROFILEDIR
ln -sf /usr/share/applications/w3a-gentoo.desktop $PROFILEDIR/epiphany-w3a-gentoo.desktop
ln -sf /usr/share/pixmaps/w3a-gentoo.png $PROFILEDIR/app-icon.png
epiphany --application-mode --profile=$PROFILEDIR $URL
